--- #YAML:1.0
name:               Log-Any-Adapter-Mojo
version:            0.01
abstract:           ~
author:
    - Henry Tang <henryykt@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Log::Any::Adapter:  0.03
    Mojolicious:        1.13
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
