---
abstract: unknown
author:
  - 'Henry Tang <henryykt@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Any-Adapter-Mojo
no_index:
  directory:
    - t
    - inc
requires:
  Log::Any::Adapter: 0.03
  Mojolicious: 1.13
version: 0.05
